import { readFileSync, writeFileSync } from 'node:fs';

const profile = JSON.parse(readFileSync(new URL('../src/data/profile.json', import.meta.url)));
const publications = JSON.parse(readFileSync(new URL('../src/data/publications.json', import.meta.url)));
const output = new URL('../cv/Kaiming_Liu_CV.tex', import.meta.url);
const tex = value => String(value).replace(/[\\{}$&#%_~^]/g, char => ({
  '\\': '\\textbackslash{}', '{': '\\{', '}': '\\}', '$': '\\$', '&': '\\&', '#': '\\#',
  '%': '\\%', '_': '\\_', '~': '\\textasciitilde{}', '^': '\\textasciicircum{}',
})[char]).replaceAll('–', '--').replaceAll('’', "'").replaceAll('š', '\\v{s}');
const link = (url, label) => String.raw`\href{${url}}{${tex(label)}}`;
const institution = item => item.url ? String.raw`\href{${item.url}}{\textcolor{black}{\textbf{${tex(item.institution)}}}}` : String.raw`\textbf{${tex(item.institution)}}`;
const entry = item => String.raw`\entry{${institution(item)}}{${tex(item.role || item.cvDegree || item.degree)}}{${tex(item.dates)}}`;
const bullets = items => String.raw`\begin{itemize}
${items.map(item => String.raw`  \item ${tex(item)}`).join('\n')}
\end{itemize}`;
const rows = (label, items) => items.map((content, i) => String.raw`\cvrow{${i === 0 ? tex(label) : ''}}{${content}}{${i === items.length - 1 ? 15 : 8}}`).join('\n');
const updated = new Intl.DateTimeFormat('en-US', { dateStyle: 'long', timeZone: 'UTC' }).format(new Date(`${profile.updated}T00:00:00Z`));
const educationGroups = Map.groupBy(profile.education, item => item.institution);
const educationBlock = rows('Education', [...educationGroups.values()].map(items => String.raw`${institution(items[0])}\par
${items.map(item => String.raw`\datedline{\textit{${tex(item.cvDegree || item.degree)}}}{\textit{${tex(item.dates)}}}
${item.note && !item.cvDegree ? tex(item.note) + String.raw`\par` : ''}`).join('\n')}`));
const experienceBlock = items => items.map(item => String.raw`${entry(item)}
${item.projects ? item.projects.map(project => String.raw`\vspace{6pt}
\textbf{${tex(project.title)}}\par
${bullets(project.bullets)}`).join('\n') : bullets(item.bullets)}`);
const teachingBlock = rows('Teaching', profile.teaching.map(item => entry(item)));
const honorsBlock = rows('Selected Honors', profile.honors.map(item => String.raw`\datedline{${tex(item.name)}}{${tex(item.year)}}
${tex(item.institution)}\par`));
const skillsBlock = rows('Technical Skills', [profile.skills.map(item => String.raw`\textit{${tex(item.category)}:} ${tex(item.items)}\par`).join('\n')]);
const paperSection = (label, papers, prefix) => papers.length ? rows(label, papers.map((paper, i) => {
  const authors = paper.authors.map(author => author === profile.name ? String.raw`\textbf{${tex(author)}}` : tex(author)).join(', ');
  const title = tex(paper.title)
    .replaceAll('orders in UTe₂', String.raw`orders~in~UTe$_2$`)
    .replaceAll('UTe₂', String.raw`UTe$_2$`);
  return String.raw`\textbf{[${prefix}${i + 1}] \href{${paper.url}}{\textcolor{black}{${title}}}}\par
${authors}.\par
\textit{${tex(paper.venue)} ${tex(paper.citation || '')} (${paper.year})}${paper.preprint ? String.raw`.\quad ${link(paper.preprint, 'arXiv')}` : ''}.\par`;
})) : '';

const source = String.raw`% Generated by scripts/generate-cv.mjs from src/data/profile.json and publications.json.
% Standalone, Overleaf-compatible. Upload this file; compile with pdfLaTeX.
% Edit canonical data and regenerate instead of editing this generated file.
\documentclass[11pt,letterpaper]{article}
\usepackage[left=0.72in,right=0.72in,top=0.68in,bottom=0.70in]{geometry}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{lmodern}
\usepackage{microtype}
\usepackage{tabularx}
\usepackage{longtable}
\usepackage{enumitem}
\usepackage{fancyhdr}
\usepackage{xcolor}
\usepackage{hyperref}
\ifdefined\pdfgentounicode
  \input{glyphtounicode}
  \pdfgentounicode=1
\fi
\definecolor{accent}{HTML}{36566F}
\definecolor{quietgray}{HTML}{666666}
\hypersetup{colorlinks=true,urlcolor=accent,linkcolor=accent,
  pdftitle={${tex(profile.name)} -- Curriculum Vitae},pdfauthor={${tex(profile.name)}}}
\urlstyle{same}
\setlength{\parindent}{0pt}
\setlength{\parskip}{1.5pt}
\setlength{\emergencystretch}{2em}
\setlength{\LTpre}{0pt}
\setlength{\LTpost}{0pt}
\setlength{\tabcolsep}{0pt}
\setlist[itemize]{leftmargin=12pt,label=\textbullet,itemsep=2pt,topsep=3pt,parsep=0pt,partopsep=0pt}
\pagestyle{fancy}
\fancyhf{}
\renewcommand{\headrulewidth}{0pt}
\fancyfoot[R]{\small\color{quietgray}\thepage}
\setlength{\footskip}{23pt}
\newcommand{\datedline}[2]{%
  \begin{tabularx}{\linewidth}{@{}>{\raggedright\arraybackslash}Xr@{}}#1&#2\end{tabularx}\par\nobreak}
\newcommand{\entry}[3]{%
  #1\par\nobreak
  \datedline{\textit{#2}}{\textit{#3}}}
\newcommand{\cvrow}[3]{%
  {\raggedright\small\sffamily\bfseries\color{accent}#1\par}&%
  \begin{minipage}[t]{\linewidth}\raggedright #2\end{minipage}\\\noalign{\vskip #3pt}}
\begin{document}
\noindent{\fontsize{29}{33}\selectfont ${tex(profile.name)}}
\hfill{\small\itshape Updated: ${updated}}\par
\vspace{7pt}
{\small
\textbf{Email:} ${link(`mailto:${profile.email}`, profile.email)}
\hfill\textbf{GitHub:} ${link(profile.github, 'github.com/kl543')}
\hfill\textbf{Homepage:} ${link(profile.website, 'kl543.github.io')}
}\par
\vspace{18pt}

% Each entry is an indivisible row; the table can break between entries.
% The left label column remains aligned throughout both pages.
\begin{longtable}{@{}p{80pt}@{\hspace{14pt}}p{\dimexpr\textwidth-94pt\relax}@{}}
${rows('Research Profile', [tex(profile.researchProfile)])}
${educationBlock}
${rows('Current Research', experienceBlock(profile.experience.slice(0, 1)))}
\end{longtable}
\newpage
\begin{longtable}{@{}p{80pt}@{\hspace{14pt}}p{\dimexpr\textwidth-94pt\relax}@{}}
${paperSection('Publications', publications.filter(paper => paper.status === 'published'), 'P')}
${paperSection('Preprints', publications.filter(paper => paper.status === 'preprint'), 'A')}
${rows('Prior Research', experienceBlock(profile.experience.slice(1)))}
${teachingBlock}
${honorsBlock}
${skillsBlock}
\end{longtable}
\end{document}
`;

if (process.argv.includes('--check')) {
  if (readFileSync(output, 'utf8') !== source) {
    throw new Error('CV source is out of date. Run npm run cv:build after editing profile or publications.');
  }
  console.log('CV source agrees with canonical content.');
} else {
  writeFileSync(output, source);
  console.log('Generated cv/Kaiming_Liu_CV.tex');
}
