import { readFileSync, writeFileSync } from 'node:fs';

const profile = JSON.parse(readFileSync(new URL('../src/data/profile.json', import.meta.url)));
const publications = JSON.parse(readFileSync(new URL('../src/data/publications.json', import.meta.url)));
const output = new URL('../cv/Kaiming_Liu_CV.tex', import.meta.url);
const tex = value => String(value).replace(/[\\{}$&#%_~^]/g, char => ({
  '\\': '\\textbackslash{}', '{': '\\{', '}': '\\}', '$': '\\$', '&': '\\&', '#': '\\#',
  '%': '\\%', '_': '\\_', '~': '\\textasciitilde{}', '^': '\\textasciicircum{}',
})[char]).replaceAll('–', '--').replaceAll('’', "'").replaceAll('š', '\\v{s}');
const link = (url, label) => `\\href{${url}}{${tex(label)}}`;
const entry = (institution, role, dates) => `\\entry{${tex(institution)}}{${tex(role)}}{${tex(dates)}}`;
const bullets = items => `\\begin{itemize}\n${items.map(item => `  \\item ${tex(item)}`).join('\n')}\n\\end{itemize}`;
const published = publications.filter(paper => paper.status === 'published');
const preprints = publications.filter(paper => paper.status === 'preprint');
const updated = new Intl.DateTimeFormat('en-US', { dateStyle: 'long', timeZone: 'UTC' }).format(new Date(`${profile.updated}T00:00:00Z`));
const educationBlock = profile.education.map(item => String.raw`${entry(item.institution, item.degree, item.dates)}
${item.note ? tex(item.note) + String.raw`\par` : ''}
\vspace{4pt}`).join('\n');
const experienceBlock = profile.experience.map(item => String.raw`${entry(item.institution, item.role, item.dates)}
${bullets(item.bullets)}
\vspace{3pt}`).join('\n');
const teachingBlock = profile.teaching.map(item => String.raw`${entry(item.institution, item.role, item.dates)}
${tex(item.text)}\par`).join('\n');
const honorsBlock = profile.honors.map(item => String.raw`\textbf{${tex(item.name)}} \hfill ${tex(item.year)}\\
${tex(item.institution)}\par`).join('\n');
const skillsBlock = profile.skills.map(item => String.raw`\textbf{${tex(item.category)}:} ${tex(item.items)}\par`).join('\n');
const paperSection = (title, papers) => papers.length ? `\\section*{${title}}\n${papers.map(paper => {
  const authors = paper.authors.map(author => author === profile.name ? `\\textbf{${tex(author)}}` : tex(author)).join(', ');
  return `${authors}.\\par\n${link(paper.url, paper.title)}. \\textit{${tex(paper.venue)}} ${tex(paper.citation || '')} (${paper.year}).${paper.preprint ? ` ${link(paper.preprint, 'arXiv version')}.` : ''}\\par\n`;
}).join('\n')}` : '';

const source = String.raw`% Generated by scripts/generate-cv.mjs from src/data/profile.json and publications.json.
% Standalone, Overleaf-compatible. Upload this file; compile with pdfLaTeX.
% Edit canonical data and regenerate instead of editing this generated file.
\documentclass[11pt,letterpaper]{article}
\usepackage[margin=0.72in]{geometry}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{lmodern}
\usepackage{microtype}
\usepackage{tabularx}
\usepackage{enumitem}
\usepackage{titlesec}
\usepackage{fancyhdr}
\usepackage{xcolor}
\usepackage{hyperref}
\ifdefined\pdfgentounicode
  \input{glyphtounicode}
  \pdfgentounicode=1
\fi
\definecolor{linkblue}{HTML}{244E7A}
\hypersetup{colorlinks=true,urlcolor=linkblue,linkcolor=linkblue,
  pdftitle={${tex(profile.name)} -- Curriculum Vitae},pdfauthor={${tex(profile.name)}}}
\urlstyle{same}
\setlength{\parindent}{0pt}
\setlength{\parskip}{3pt}
\setlength{\emergencystretch}{2em}
\renewcommand{\baselinestretch}{1.03}
\titleformat{\section}{\large\bfseries}{}{0pt}{}
\titlespacing*{\section}{0pt}{13pt}{6pt}
\setlist[itemize]{leftmargin=15pt,itemsep=3pt,topsep=4pt,parsep=0pt}
\pagestyle{fancy}
\fancyhf{}
\renewcommand{\headrulewidth}{0pt}
\fancyfoot[L]{\footnotesize ${tex(profile.name)} \quad | \quad Updated ${updated}}
\fancyfoot[R]{\footnotesize \thepage}
\setlength{\footskip}{24pt}
\newcommand{\entry}[3]{%
  \noindent\begin{tabularx}{\linewidth}{@{}Xr@{}}\textbf{#1}&{\small #3}\end{tabularx}\par\nobreak
  {\itshape #2}\par\nobreak}
\begin{document}
{\LARGE ${tex(profile.name)}}\par
${tex(profile.title)}, ${tex(profile.institution)}\par
${link(`mailto:${profile.email}`, profile.email)} \enspace $\cdot$ \enspace
${link(profile.website, 'kl543.github.io')} \enspace $\cdot$ \enspace
${link(profile.github, 'GitHub')} \enspace $\cdot$ \enspace
${link(profile.linkedin, 'LinkedIn')}

\section*{Research Interests}
${tex(profile.interests)}

\section*{Education}
${educationBlock}

\section*{Research Experience}
${experienceBlock}

${paperSection('Publications', published)}
${paperSection('Preprints', preprints)}

\section*{Teaching}
${teachingBlock}

\section*{Selected Honors}
${honorsBlock}

\section*{Technical Skills}
${skillsBlock}
\end{document}
`;

if (process.argv.includes('--check')) {
  if (readFileSync(output, 'utf8') !== source) {
    throw new Error('CV source is out of date. Run npm run cv:build after editing profile or publications.');
  }
  console.log('CV source agrees with canonical content.');
} else {
  writeFileSync(output, source);
  console.log('Generated cv/Kaiming_Liu_CV.tex');
}
